version: '3'

services:
  app:
    container_name: backend
    build:
      context: .
    networks:
      - app_tier
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env.dev

  redis1:
    container_name: redis_for_session
    image: redis:alpine
    networks:
      - app_tier

  redis2:
    container_name: redis_for_broker
    healthcheck:
        test: "redis-cli -h 127.0.0.1 ping"            
        interval: 3s
        timeout: 1s
        retries: 5
    image: redis:alpine
    networks:
      - app_tier

  celery:
    container_name: celery
    restart: always
    networks:
      - app_tier
    build:
      context: .
    command: celery -A app worker --loglevel=info
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - redis2
      - app
  
  # web server
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - app_tier
    ports:
      - 80:3000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: on-failure

networks:
  app_tier:
    driver: bridge