# Generated by Django 3.1 on 2022-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221009_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
