# Generated by Django 3.1 on 2022-10-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videoinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='image_ext',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='status_detail',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
